# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-26 20:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0002_auto_20160726_1539'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='cantidad')),
                ('product', models.ManyToManyField(to='products.ProductCatalog')),
            ],
        ),
        migrations.CreateModel(
            name='ServicesCatalog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=60, verbose_name='servicio')),
                ('description', models.CharField(blank=True, max_length=120, null=True, verbose_name='descripci\xf3n')),
                ('domicilie', models.BooleanField(default=False, verbose_name='a domicilio')),
                ('store', models.BooleanField(default=True, verbose_name='en sucursal')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='precio')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='productservice',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.ServicesCatalog'),
        ),
        migrations.AddField(
            model_name='productservice',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
