# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-29 22:52
from __future__ import unicode_literals

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='profiles', verbose_name='Foto')),
                ('telephone', models.CharField(blank=True, max_length=15, null=True, verbose_name='Tel\xe9fono')),
                ('services', models.IntegerField(blank=True, null=True, verbose_name='Servicios solicitados')),
                ('score', models.FloatField(blank=True, null=True, verbose_name='Calificacion')),
                ('reg_date', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                (
                'user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Perfil de usuarios',
            },
        ),
    ]
