# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-13 21:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='score',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='services',
            field=models.IntegerField(null=True),
        ),
    ]
