# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-13 21:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('accounts', '0002_auto_20160613_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='services',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
