# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-14 23:45
from __future__ import unicode_literals

import datetime

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0003_auto_20160613_1631'),
    ]

    operations = [
        migrations.CreateModel(
            name='CitiesCatalog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='PostalCodeCatalog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postal_code', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='StatesCatalog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='SuburbCatalog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suburb', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=150)),
                ('crossing_x', models.CharField(blank=True, max_length=150, null=True)),
                ('crossing_y', models.CharField(blank=True, max_length=150, null=True)),
                ('CP',
                 models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.PostalCodeCatalog')),
                (
                    'city',
                    models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.CitiesCatalog')),
                ('state',
                 models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.StatesCatalog')),
                ('suburb',
                 models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.SuburbCatalog')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='reg_date',
            field=models.DateTimeField(auto_now=True,
                                       default=datetime.datetime(2016, 6, 14, 23, 45, 16, 768000, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='telephone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
