# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-15 00:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('accounts', '0004_auto_20160614_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postalcodecatalog',
            name='postal_code',
            field=models.CharField(max_length=10),
        ),
    ]
