# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-15 21:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('accounts', '0006_auto_20160615_0847'),
    ]

    operations = [
        migrations.AddField(
            model_name='suburbcatalog',
            name='code',
            field=models.CharField(default=97314, max_length=10),
            preserve_default=False,
        ),
    ]
