# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-15 22:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_useraddress_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraddress',
            old_name='CP',
            new_name='postal_code',
        ),
    ]
