# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-04 23:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCatalog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=80, verbose_name='etiquetas')),
                ('product_name', models.CharField(max_length=80, verbose_name='nombre del producto')),
                ('patent', models.CharField(max_length=80, verbose_name='marca')),
                ('series', models.CharField(blank=True, max_length=20, null=True, verbose_name='serie')),
                ('origin', models.CharField(blank=True, max_length=20, null=True, verbose_name='origen')),
                ('net', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='contenido')),
                ('measure', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='medida')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Catalogo de productos',
            },
        ),
    ]
