# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-08 23:17
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EntryOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_ref', models.CharField(max_length=20, verbose_name='referencia')),
                ('date_order', models.DateTimeField(auto_now=True, verbose_name='fecha')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='precio total')),
                ('entry_date', models.DateTimeField(verbose_name='fecha entrega')),
                ('payment_order', models.BooleanField(default=False, verbose_name='pagado')),
                ('entry', models.BooleanField(default=False, verbose_name='entregado')),
            ],
            options={
                'verbose_name_plural': 'Pedido',
            },
        ),
        migrations.CreateModel(
            name='EntryOrderDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_order', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='cantidad ordenada')),
                ('piece_price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='precio unidad')),
                ('order_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.EntryOrder')),
            ],
            options={
                'verbose_name_plural': 'Detalle de Pedido',
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='cantidad')),
                ('entry', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='entradas')),
                ('date_entry', models.DateTimeField(auto_now=True, verbose_name='Fecha de entrada')),
                ('out', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='salidas')),
                ('entry_price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='precio entrada')),
                ('out_price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='precio salida')),
                ('percent_desc', models.IntegerField(validators=[django.core.validators.MaxValueValidator(99)], verbose_name='porcentaje oferta')),
            ],
            options={
                'verbose_name_plural': 'Inventario',
            },
        ),
        migrations.CreateModel(
            name='OutOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_ref', models.CharField(max_length=20, verbose_name='referencia')),
                ('client', models.CharField(max_length=30, verbose_name='cliente')),
                ('date_order', models.DateTimeField(auto_now=True, verbose_name='fecha orden')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='precio total')),
                ('entry_date', models.DateTimeField(verbose_name='fecha venta')),
                ('payment_order', models.BooleanField(default=False, verbose_name='pagado')),
                ('entry', models.BooleanField(default=False, verbose_name='entregado')),
                ('description', models.CharField(max_length=80, verbose_name='descripci\xf3n')),
            ],
            options={
                'verbose_name_plural': 'Salida de producto',
            },
        ),
        migrations.CreateModel(
            name='OutOrderDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_order', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='cantidad vendidas')),
                ('piece_price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='precio unidad')),
                ('order_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.OutOrder')),
            ],
            options={
                'verbose_name_plural': 'Detalle de salida de producto',
            },
        ),
        migrations.CreateModel(
            name='PaymentCatalog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(max_length=30, verbose_name='forma de pago')),
                ('description', models.CharField(max_length=80, verbose_name='descripcion')),
            ],
            options={
                'verbose_name_plural': 'Forma de pagos',
            },
        ),
        migrations.CreateModel(
            name='ProducerCatalog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producer', models.CharField(blank=True, max_length=40, null=True, verbose_name='productor')),
                ('country', models.CharField(max_length=40, verbose_name='pa\xeds')),
            ],
            options={
                'verbose_name_plural': 'Catalogo de productores',
            },
        ),
        migrations.CreateModel(
            name='ProductCatalog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('product_name', models.CharField(max_length=80, verbose_name='nombre del producto')),
                ('patent', models.CharField(blank=True, max_length=80, null=True, verbose_name='marca')),
                ('series', models.CharField(blank=True, max_length=20, null=True, verbose_name='serie')),
                ('origin', models.CharField(blank=True, max_length=20, null=True, verbose_name='origen')),
                ('net', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='contenido')),
                ('measure', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='medida')),
                ('barcode', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(999999999999999L)], verbose_name='c\xf3digo de barras')),
                ('producer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.ProducerCatalog')),
            ],
            options={
                'verbose_name_plural': 'Catalogo de productos',
            },
        ),
        migrations.CreateModel(
            name='ProviderCatalog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='nombre')),
                ('RFC', models.CharField(blank=True, max_length=13, null=True)),
                ('registry_date', models.DateTimeField(auto_now=True, verbose_name='fecha registro')),
                ('facture_name', models.CharField(blank=True, max_length=40, null=True, verbose_name='Nombre facturaci\xf3n')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='email')),
                ('web', models.CharField(blank=True, max_length=200, null=True, verbose_name='Pagina web')),
                ('telephone', models.CharField(blank=True, max_length=30, null=True, verbose_name='Tel\xe9fono')),
            ],
            options={
                'verbose_name_plural': 'Catalogo de proveedores',
            },
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cash', models.CharField(max_length=40, verbose_name='caja')),
                ('date_sale', models.DateTimeField(auto_now=True, verbose_name='fecha venta')),
                ('total', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='total')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.PaymentCatalog')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Ventas',
            },
        ),
        migrations.CreateModel(
            name='SalesDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='cantidad')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='precio')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.ProductCatalog')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Sales')),
            ],
            options={
                'verbose_name_plural': 'Detalle de venta',
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='nombre')),
                ('description', models.CharField(blank=True, max_length=120, null=True, verbose_name='descripci\xf3n')),
            ],
            options={
                'verbose_name_plural': 'Almac\xe9n',
            },
        ),
        migrations.AddField(
            model_name='productcatalog',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.ProviderCatalog'),
        ),
        migrations.AddField(
            model_name='productcatalog',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='outorderdetail',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='products.ProductCatalog'),
        ),
        migrations.AddField(
            model_name='outorder',
            name='payment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='products.PaymentCatalog'),
        ),
        migrations.AddField(
            model_name='outorder',
            name='store',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='products.Store'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.ProductCatalog'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Store'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='entryorderdetail',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.ProductCatalog'),
        ),
        migrations.AddField(
            model_name='entryorder',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.PaymentCatalog'),
        ),
        migrations.AddField(
            model_name='entryorder',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.ProviderCatalog'),
        ),
        migrations.AddField(
            model_name='entryorder',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Store'),
        ),
        migrations.AddField(
            model_name='entryorder',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
